-- A temporary table for instrumenting a manual QA pass.
--
-- Production is serverless, so there is no local disk that survives a request;
-- an observation has to land somewhere shared to be readable afterwards.
--
-- It holds no values anybody typed — element descriptions and form field
-- *names* only. A QA log that accumulated customer details would be a second
-- copy of that data governed by none of the retention rules that cover the
-- first, which is the opposite of what this project spent its retention work on.
--
-- `0020_drop_qa_event.sql.pending` is written and waiting. Apply it when the
-- pass is done; nothing else in the schema references this table.
--
-- Generated by drizzle-kit, not hand-written: a CREATE TABLE also needs its
-- snapshot in `meta/`, and CI fails on the drift a hand-written one leaves.
CREATE TABLE "qa_event" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"session" text NOT NULL,
	"seq" integer NOT NULL,
	"kind" text NOT NULL,
	"path" text NOT NULL,
	"target" text,
	"field" text,
	"detail" text,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "qa_event_session_seq_idx" ON "qa_event" USING btree ("session","seq");